### PR TITLE
Fix css syntax

### PR DESCRIPTION
**Pull request by myw**
I was getting errors in Vim 7.4 upon startup:

```
Error detected while processing […]/syntax/css.vim:
line   15:
E409: Unknown group name: cssValue.*,cssColor,cssURL,cssImportant,cssError,cssStringQ,cssStringQQ,cssFunction,cssUnicodeEscape,cssVendor,cssDefinition,cssHacks,cssNo
ise,cssMixinDefinition,cssMixinName,cssApplyRegion,cssApplyName fold
E475: Invalid argument: cssMixinDefinition contained transparent matchgroup=cssBraces start="\(^\|;\|\s\)--[a-zA-Z_][a-zA-Z0-9_-]*\>:\s*\zs{" end="}" contains=cssDef
inition,cssAttrRegion,cssMixinName,cssAttrRegion,css.*Prop,cssComment,cssValue.*,cssColor,cssURL,cssImportant,cssError,cssStringQ,cssStringQQ,cssFunction,cssUnicodeE
scape,cssVendor,cssDefinition,cssHacks,cssNoise,cssMixinDefinition,cssMixinName,cssApplyRegion,cssApplyName fold
line   21:
E409: Unknown group name: cssValue.*,cssColor,cssURL,cssImportant,cssError,cssStringQ,cssStringQQ,cssFunction,cssUnicodeEscape,cssVendor,cssDefinition,cssHacks,cssNo
ise,cssMixinDefinition,cssMixinName,cssApplyRegion,cssApplyName fold
E475: Invalid argument: cssDefinition transparent matchgroup=cssBraces start='{' end='}' contains=cssAttrRegion,css.*Prop,cssComment,cssValue.*,cssColor,cssURL,cssIm
portant,cssError,cssStringQ,cssStringQQ,cssFunction,cssUnicodeEscape,cssVendor,cssDefinition,cssHacks,cssNoise,cssMixinDefinition,cssMixinName,cssApplyRegion,cssAppl
yName fold
line   24:
E409: Unknown group name: css.*Attr,cssColor,cssImportant,cssValue.*,cssFunction,cssString.*,cssURL,cssComment,cssUnicodeEscape,cssVendor,cssError,cssAttrComma,cssNo
ise
E475: Invalid argument: cssAttrRegion contained start=/:\(\s*{\)\@!/ end=/\ze\(;\|)\|}\)/ contained contains=css.*Attr,cssColor,cssImportant,cssValue.*,cssFunction,c
ssString.*,cssURL,cssComment,cssUnicodeEscape,cssVendor,cssError,cssAttrComma,cssNoise
```

This seems to be due to the `cssValue.*` part of the `contains` parameters of the `syn match` commands in the `css.vim` file—I'm not exactly sure why; from the Vim documentation, it seems like `cssValue.*` should work; nevertheless, putting quotes around it gets rid of the errors.

I've also cleaned up a bit of the lines for legibility purposes.

### CODE REVIEW

**Comment by dafky2000** [comment]
Fixed the same issues in v7.4.1797 - Thanks for the patch, hopefully it gets merged in!

**Comment by cwonrails** [comment]
Great work @myw - same results as @dafky2000 but with v7.4.1817. @bendavis78 any chance we could get a merge?

**Comment by fearphage** [comment]
This fixes #2. 

I'm assuming the project is abandoned at this point... after 4 months of silence and 9 months of no commits.

**Comment by myw** [comment]
Since this project does indeed seem like nothing is happening, I've merged the changes into my main branch. My fork will continue to be up-to-date and have other improvements.

Cheers!

**Comment by webdesus** [comment]
I wrote plugin [polymer-ide](https://github.com/webdesus/polymer-ide.vim). I will happy if you help me make this plugin more powerfull(like sample add linting)
Current features:

- typeahead completions for imported elements, with documentation 
- typeahead completions for element attributes, with documentation 
- inline errors (marks on lines) 
- jump to definition support for custom elements and attributes

**Pull request merged**
